cat \
Tex/Frontpages.tex \
Tex/Chap_Intro.tex \
Tex/Chap_Pre.tex \
Tex/Chap_Pheno.tex \
Tex/Chap_LHC.tex \
Tex/Chap_ATLAS.tex \
Tex/Chap_ITk.tex \
Tex/Chap_EvtReco.tex \
Tex/Chap_EvtSim.tex \
Tex/Chap_ttHIntro.tex \
Tex/Chap_1l2tau.tex \
Tex/Chap_tthStat.tex \
Tex/Chap_ResultsttH.tex \
Tex/Chap_hhIntro.tex \
Tex/Chap_DataMC.tex \
Tex/Chap_EvtSel.tex \
Tex/Chap_BkgEstimation.tex \
Tex/Chap_Optimization.tex \
Tex/Chap_Systematics.tex \
Tex/Chap_Stat.tex \
Tex/Chap_4Wcomb.tex \
Tex/Chap_hhComb.tex \
Tex/Chap_Con.tex \
Tex/Backmatter.tex > Tex/merged.txt 
